### ISSUE TITLE
Feature request: EVENT_LEFT_LIST_CLEARED and EVENT_RIGHT_LIST_CLEARED

### ISSUE THREAD

**Issue by Baertram** [klingo/ESO-LibShifterBox#15]
I'd like to get additional callbacks as the left or right lists get cleared.
The purpose is to re-load default items into the lists, or execute some check functions.

Currently I have to manually check this via the other EVENT_ENTRY_MOVED callback by getting and checking the list contents.
But I also have to check the same as shifterbox:ClearLeftList() or shifterBox:ClearRightList() are called.

A callback for all cases would be easier to handle.

Many thanks

**Comment by klingo** [comment]
I was thinking a bit about this and am not sure yet how to handle this when there are entries from different categories in a list. 
For example I have a shifterBox where I add all the entries for the different weaponTypes (Sword, Dagger, Axe, ...) and also all the equipTypes (Head, Gloves, Pants, ...) but under a different category.
Depending on another selection I can now either show/hide all weaponTypes in that shifterBox, or the equpTypes without the need to remove all weapons and add all equiptypes (and vice versa). Theoretically you can also hide all categories, or show multiple/all of them.

Now regarding the LIST_CLEARED event it gets interesting: When should this be triggered?
When really ALL entries are removed from the list (including the ones from a hidden catgory), or only when all "visible" entries have been removed? I think both need to be supported - but I am not sure if I really want to make two different events for this, or one event that is triggered in both cases but it returns a boolean-flag like "hasStillHiddenEntries" that the consumer can check.

What is your opinion on that?

**Comment by Baertram** [comment]
Hm, I'd say only the total clear should be taken into account for this event "cleared".
I personally do not care about invisible entries but I need to know if the list got no entry because someone removed all items.
If someone just hides entries this could be usefull for other usecases as well. But I'm syning the entries with SavedVariables and do not need to hide entries, it's just a true/false in the SV (in my case).

I like the idea with the callback function of the event automatically providing a parameter/variable which tells us the state of the list, like isListFinallyCleared or isListStillHidingEntries or as you said hasStillHiddenEntries.

**Comment by Baertram** [comment]
Thank you very much!
